### ISSUE TITLE
White bar flashes just below nav menu when scrolling

### ISSUE THREAD

**Issue by chadfry** [Macroscope-Software/website#37]
- it's happening on both my and Anuj's computer
- it's a very brief flash of white that spans the entire width of the page and is about 20px thick
- it only shows when user scrolls down and then quickly back to the top

**Comment by apoorvmacroscope** [comment]
This is happening because we have placed a non-fixed header over fixed header. So when user scrolls then top header gets removed and comes back and due to this it occupies and releases space again and again. So according to my suggestion we should show full header including top and bottom one instead of hiding top one. Please check following screenshot : http://prntscr.com/7qldel

**Comment by chadfry** [comment]
Thats a great idea Apoorv. Thanks!

**Comment by chadfry** [comment]
It's still happening on my desktop. Could it be because of overscrolling? http://stackoverflow.com/questions/12046315/prevent-overscrolling-of-web-page

**Comment by apoorvmacroscope** [comment]
I don't think that's issue of over scrolling. I have fixed it now, please check and confirm if it works fine.

**Comment by chadfry** [comment]
Yup, it's fixed on desktop, but still happening on mobile (Safari, Iphone5)

**Comment by apoorvmacroscope** [comment]
ok I will check on iPhone and let you know.

**Comment by chadfry** [comment]
Any progress on this Apoorv?

**Comment by chadfry** [comment]
It's happening only in Safari on mobile and desktop it seems
